### ISSUE TITLE
Make sure all tests functional again.

### ISSUE THREAD

**Issue by lily-seabreeze** [lily-seabreeze/sappho#60]
Slowly copy over the `old_tests/test_animatedsprite.py` to `new_tests/` and make sure all the tests work! BONUS: test anchoring system.

**Comment by kcsaff** [comment]
Animated sprite tests work, but relatively low code coverage

**Comment by lillian-gardenia-seabreeze** [comment]
Issue #63 related

**Comment by lily-seabreeze** [comment]
I think mayeb this is referring to some tests being inaccurate? I wonder if this is still true...
