### ISSUE TITLE
fix/finish/redo anchoring system

### ISSUE THREAD

**Issue by lily-seabreeze** [lily-seabreeze/sappho#62]
this would imply having a function that generates the anchorskeleton object from a surface? right now it's kind of a web of being generated... whereas you could have a function that could iterate through a list of surfaces to generate anchorskeletons for.

make anchoring system compatible with non-animated sprites

**Comment by lillian-gardenia-seabreeze** [comment]
remove anchor stuff from animatedsprite, put in own module.

**Comment by txanatan** [comment]
possible way to redo anchoring would be something modeled after [osu!'s anchoring system](http://blog.ppy.sh/post/140087699883/sprites-and-containers-in-osu) which is extremely versatile. could be used for sprites as well as actual game UI stuff

**Comment by lillian-gardenia-seabreeze** [comment]
see #66
